### PR TITLE
Scan more often

### PR DESCRIPTION
**Pull request by rkuris**

### CODE REVIEW

**Comment by deba168** [comment]
Hi Ron Kuris,
Can you tell me what modification you have done to the code ?

_Thanks *
*Debasish_

**Comment by rkuris** [comment]
Thank you for approving my pull request! Your design and explanations are really good, and I'm in the process of soldering together my components from a breadboard.

When I made the commits, I added these comments, which describe the changes.

```
The code previously scanned fairly rarely due to the thingspeak code long delay.
Now it scans every second or so, making adjustments to the PWM more frequent.
This code also adds a spinner so you can verify that it's adjusting things.

Started moving some of the constants on the display to the initialization section.
Computed things instead of having some big switch-like statements.
```

The primary reason for my changes is that I want to use this schematic for the solar controller on my boat, but it will need to react a lot faster to changing battery and solar conditions. The long delay in the thingspeak code was my biggest problem.

Here are some other changes I'd like to make:
- Adjust the battery voltage divider so it supports a maximum voltage of about 17V. Currently it supports a maximum voltage of 35V, the same as the solar input. To do this, I intend to replace R4 with a 47k resistor and make some minor code changes
- Support disabling web logging both at compile time or at runtime via a switch. I think you have two copies of the same code and it would be easier to just have one, but please correct me if that's not correct.
- Change the battery icon so it shows the percentage full instead of just always appearing as a half-full battery. I think I can create several icons and switch between them based on state, giving a much nicer presentation.
- Modify the LED display to have 5 states - GREEN, GREEN/YELLOW, YELLOW, YELLOW/RED and RED. I want the RED led to flash as well so I know when I'm low on charge.

I have some other ideas but would like to hear from you if you think these are good ideas or not!

**Comment by deba168** [comment]
Thank you for quick reply.
Your ideas are really great.Regarding the battery icon display I am also
think to display as per the battery voltage.I will very happy if we will work
together.
I am planning to make version-4 of charge controller with higher power
handling capability.You can see our ideas and planning.I would like to
share your suggestions and ideas there ( at comment section) .I may need
help from you for my v-4 controller coding.
https://hackaday.io/project/4613-arduino-mppt-solar-charge-controller/log/19267-version-4-design-ideas-and-planning

Regard
Debasish

**Comment by rkuris** [comment]
My electronic design is not as good as yours, but I have a lot of experience with embedded programming and software design. I would be happy to help with the software changes.

It does look like this circuit can definitely work with a 10A or even a 20A solar array with very few changes. I didn't make the switched output load circuit because I am just using a 25A solid state relay and heat sink. My use case for the switched load is different; I want to dump the excess solar energy i
after the battery is fully charged into a peltier to help keep my beer cold on hot sunny days.

**Comment by deba168** [comment]
Thank you so much for showing interest to help me. Its good news for me as I was searching for friend who have good skill on embedded coding.Our planning for V-4 controller should charge different battery types, such as Lead Acid (several variants), NiFe, LiFePO etc. As per my knowledge the same hardware can do the job.Only we have to write separate charging algorithm for different battery chemistry.When our design parameters are finalised I need your help for doing this job.

**Comment by deba168** [comment]
Can you modify one thing in the ESP8266 code ? .In the existing code, first I connect the ESP8266 module to my router by entering the ssid and password,then upload the code to arduino.I need the code should option for entering SSID and Passwoed,so that when user upload the code to arduino,the ESP8266 module connect to the router automatically.
Thanks

**Comment by rkuris** [comment]
I created issue https://github.com/deba168/MPPT_Master/issues/4 for this. My controller is being soldered right now so it will be a day or two before I will have the ESP8266 up and running again to be able to test these changes.

**Pull request merged**
