### PR TITLE
Battery icon improvements

### PR DESCRIPTION
**Pull request by rkuris**
@deba168 this gives you a better battery icon. It works great, let me know if you want to see a video of it operating.

I also changed the code to support having a different load control algorithm. You are probably using solar just for lighting, but I want to take excess power and use it, but I don't want my battery to run down at all.

### CODE REVIEW

**Comment by deba168** [comment]
I am really excited to see the operation videos.
Have you changed anything in current sensor code?
I think it needs some improvement.
I want the complete load control code also.Though it is not
important for me but it will be helpful for other.
Please send a fully modified code to my mail.
Now we have to solve the ESP8266 part.
Thanks.

**Comment by rkuris** [comment]
@deba168 here's a video of one of my tests https://www.youtube.com/watch?v=nDfRm2a05-U

**Comment by deba168** [comment]
Have you connected the solar panel ? Or it is simulation.I did not see any change in Current.

**Comment by rkuris** [comment]
I have the current sense pin shorted to 5v during this test, so it looks
like max current. This is just a test on the bench.

**Comment by deba168** [comment]
Ok got it :)
Is there any problem in MOSFET ( Shorting Q3) during the test ?
Can you test it by connecting a solar panel and battery ?
One more thing can be improved in sensor reading.In the existing code sensors are calibrated by  in term of 5.0V/1024.The problem is that if due to any reason the Vcc  is not 5.0 V the sensor reading are incorrect.So it is better to use Reference voltage instead of Vcc.It will remove the errors in reading.

**Comment by rkuris** [comment]
I have not tested the MOSFET shorting problem. However, I think I fixed it
because the system now starts OFF and doesn't turn on until several passes
through the loop. I think the biggest problem with destroying the MOSFETs
has to do with the ringing and voltage overshoot. I will be hooking up the
circuit to a scope sometime soon and making some changes.

It is not easy for me to test the system with solar and battery yet. I
don't have any sunlight or a solar panel where I live, so I have to do that
on my boat, where I don't have a lot of electronic equipment.

Your 5V reference voltage is going to cause some errors. The voltage
regular you've picked does not have a very good adjustment potentiometer so
it's very hard to get exactly 5V. I was thinking of replacing the
potentiometer with a 10 turn one. However, you might still see some drift
with temperature changes. I am not sure how much difference these errors
will make. Battery float voltages change with temperature as well.

**Pull request merged**
